sudo apt-get install \
frei0r-plugins-dev \
flite1-dev \
ladspa-sdk \
libasound2-dev \
libass-dev \
libasyncns-dev \
libattr1-dev \
libavc1394-dev \
libbluray-dev \
libbse-dev \
libbz2-dev \
libcaca-dev \
libcap-dev \
libcdio-cdda-dev \
libcdio-paranoia-dev \
libdbus-1-dev \
libdirectfb-dev \
libexpat1-dev \
libffi-dev \
libflac-dev \
libfontconfig1-dev \
libfreetype6-dev \
libfribidi-dev \
libgme-dev \
libgmp-dev \
libgnutls-dev \
libgpg-error-dev \
libgpm-dev \
libgsm1-dev \
libgusb-dev \
libice-dev \
libiec61883-dev \
libjson0-dev \
libmodplug-dev \
liblua5.1-dev \
liblzma-dev \
libmp3lame-dev \
libncursesw5-dev \
libogg-dev \
libopenal-dev \
libopencore-amrnb-dev \
libopencore-amrwb-dev \
libopencv-dev \
libopenjpeg-dev \
libopus-dev \
liborc-0.4-dev \
libp11-dev \
libpng12-dev \
libpulse-dev \
libquvi-dev \
librtmp-dev \
libsasl2-dev \
libschroedinger-dev \
libsdl1.2-dev \
libshine-dev \
libslang2-dev \
libsm-dev \
libsndfile1-dev \
libsoxr-dev \
libspeex-dev \
libssh-dev \
libtasn1-6-dev \
libtheora-dev \
libtinfo-dev \
libts-dev \
libtwolame-dev \
libusb-dev \
libv4l-dev \
libvo-aacenc-dev \
libvo-amrwbenc-dev \
libvorbis-dev \
libvpx-dev \
libwavpack-dev \
libwebp-dev \
libwrap0-dev \
libx11-dev \
libx264-dev \
libxau-dev \
libxcb1-dev \
libxdmcp-dev \
libxext-dev \
libxi-dev \
libxml2-dev \
libxtst-dev \
libxv-dev \
libxvidcore-dev \
libzmq-dev \
libzvbi-dev \
nettle-dev \
ocl-icd-opencl-dev \
uuid-dev \
zlib1g-dev \
libvpx-dev \
libgpg-error-dev \
libkeyutils-dev \
libc6-dev \
comerr-dev \
liblzma-dev \
libbz2-dev \
uuid-dev \
libexpat1-dev \
libjson-c-dev \
libdbus-1-dev \
libslang2-dev \
libtinfo-dev \
heimdal-dev \
libgl1-mesa-swx11-dev \
