##########################################################################
#
# Dezi's CentOS mock ups.
#

all: update daemons

daemons: 

##########################################################################
#
# Update and upgrade system
#

update:
	#sudo yum update
	#sudo yum upgrade
	sudo yum install -y \
		flex \
		bison \
		subversion \
